name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Prerequisites
        run: ./scripts/install-prereqs.sh
      - name: Run tests
        run: pytest
      - name: Build a Rust package via colcon
        run: ./scripts/build-rust-package.sh
